import {
  HomePage,
  EventsPage,
  AchievementsPage,
  AboutPage,
  ContactPage,
  TeamPage,
  GalleryPage,
  HighlightsPage,
} from "../pages";

export const routesConfig = [
  {
    id: "home",
    title: "Home",
    path: "/",
    alias: "/home",
    component: HomePage,
    entryFile: "src/pages/home/HomePage.jsx",
    cssFiles: ["src/styles/home.css"],
    subComponents: [
      "src/components/home/Hero.jsx",
      "src/components/home/WhyJoin.jsx",
      "src/components/home/Partners.jsx",
      "src/components/home/ContactModal.jsx",
    ],
    sharedComponents: [
      "src/components/shared/Navbar.jsx",
      "src/components/shared/Footer.jsx",
      "src/components/shared/InteractiveBackground.jsx",
    ],
  },
  {
    id: "events",
    title: "Events",
    path: "/events",
    component: EventsPage,
    entryFile: "src/pages/events/EventsPage.jsx",
    cssFiles: ["src/styles/events.css"],
    subComponents: [
      "src/components/events/Hero.jsx",
      "src/components/events/EventsSection.jsx",
      "src/components/events/EventCard.jsx",
    ],
    dataDependencies: ["src/data/events.js"],
    assetDependencies: ["src/assets/Events/"],
    sharedComponents: [
      "src/components/shared/Navbar.jsx",
      "src/components/shared/Footer.jsx",
      "src/components/shared/InteractiveBackground.jsx",
    ],
  },
  {
    id: "achievements",
    title: "Achievements",
    path: "/achievements-page",
    component: AchievementsPage,
    entryFile: "src/pages/achievements/AchievementsPage.jsx",
    cssFiles: ["src/styles/achievements.css"],
    subComponents: [
      "src/components/achievements/hero.jsx",
      "src/components/achievements/achievement.jsx",
      "src/components/achievements/timeline.jsx",
      "src/components/achievements/card.jsx",
      "src/components/achievements/fame.jsx",
      "src/components/achievements/gallery.jsx",
    ],
    sharedComponents: [
      "src/components/shared/Navbar.jsx",
      "src/components/shared/Footer.jsx",
      "src/components/shared/InteractiveBackground.jsx",
    ],
  },
  {
    id: "about",
    title: "About Us",
    path: "/about",
    component: AboutPage,
    entryFile: "src/pages/about/AboutPage.jsx",
    cssFiles: ["src/styles/about.css"],
    subComponents: [
      "src/components/about/hero.jsx",
      "src/components/about/purpose.jsx",
      "src/components/about/presidents.jsx",
      "src/components/about/departmentHeads.jsx",
      "src/components/about/contributors.jsx",
      "src/components/about/gallery.jsx",
      "src/components/about/faq.jsx",
    ],
    sharedComponents: [
      "src/components/shared/Navbar.jsx",
      "src/components/shared/Footer.jsx",
      "src/components/shared/InteractiveBackground.jsx",
    ],
  },
  {
    id: "team",
    title: "Team",
    path: "/team",
    component: TeamPage,
    entryFile: "src/pages/team/TeamPage.jsx",
    cssFiles: ["src/styles/team.css"],
    dataDependencies: ["src/data/mockData.js"],
    sharedComponents: [
      "src/components/shared/Navbar.jsx",
      "src/components/shared/Footer.jsx",
      "src/components/shared/InteractiveBackground.jsx",
    ],
  },
  {
    id: "gallery",
    title: "Gallery",
    path: "/gallery",
    component: GalleryPage,
    entryFile: "src/pages/gallery/GalleryPage.jsx",
    cssFiles: ["src/styles/gallery.css"],
    dataDependencies: ["src/data/mockData.js"],
    sharedComponents: [
      "src/components/shared/Navbar.jsx",
      "src/components/shared/Footer.jsx",
      "src/components/shared/InteractiveBackground.jsx",
    ],
  },
  {
    id: "highlights",
    title: "Highlights",
    path: "/highlights",
    alias: "/achievements",
    component: HighlightsPage,
    entryFile: "src/pages/highlights/HighlightsPage.jsx",
    cssFiles: ["src/styles/highlights.css"],
    dataDependencies: ["src/data/highlightsData.js"],
    assetDependencies: ["src/assets/Events/"],
    sharedComponents: [
      "src/components/shared/Navbar.jsx",
      "src/components/shared/Footer.jsx",
      "src/components/shared/InteractiveBackground.jsx",
    ],
  },
  {
    id: "contact",
    title: "Contact Us",
    path: "/contact",
    component: ContactPage,
    entryFile: "src/pages/contact/ContactPage.jsx",
    cssFiles: ["src/styles/contact.css"],
    sharedComponents: [
      "src/components/shared/Navbar.jsx",
      "src/components/shared/Footer.jsx",
      "src/components/shared/InteractiveBackground.jsx",
    ],
  },
];

export default routesConfig;
